# Tell Hugo to build into docs/ for GitHub Pages
publishDir   = "docs"

baseURL      = "https://techwiki.online/"
title        = "TechWiki"
theme        = "techwiki-theme"
languageCode = "en-us"

[pagination]
  pagerSize = 10

# RSS on the home page
outputs      = { home = ["HTML", "RSS"] }

[params]
  description = "The definitive encyclopedia of high‑end tech products"
  author      = "Your Name"
  adsenseID   = "ca-pub-XXXXXXXXXXXX"
  prebidID    = "/js/prebid.js"

[taxonomies]
  category = "categories"
  tag      = "tags"

# Main navigation menu
[[menu.main]]
  name   = "Home"
  url    = "/"
  weight = 1

[[menu.main]]
  name   = "Products"
  url    = "/products/"
  weight = 2

[[menu.main]]
  name   = "Compare"
  url    = "/compare/"
  weight = 3

[[menu.main]]
  name   = "Blog"
  url    = "/post/"
  weight = 4

[markup]
  defaultMarkdownHandler = "goldmark"
